### ISSUE TITLE
The Last 4 Versions of CHIRP no Longer work on Ubuntu 18.04.6 MATE & above (versions  20240413, 20240427, 20240502, 20240504, 20240514), 20241227

### ISSUE THREAD

**Issue by leirbag28** [goldstar611/chirp-appimage#7]
05-14-24 EDIT #2 STILL not working as of version 2024010 
05-04-24 EDIT #2 Just checked CHIRP-NEXT 2024-05-04 and this ALSO still does not work...that is 4 versions in a row now.
05-02-24  EDIT:  Just checked today's versions and it also does not work along with the last 2 versions.

What was changed on CHIRP the last 2 versions? because they give this error when I make the Appimage executable and drop it into the Terminal to see what it outputs (pasted here below): PLEASE fix this!  are you now compiling the Appimage on a NEWER version of Ubuntu? as that will no longer make it a Universal app (it should be compiled on CentOS or Ubuntu 16.04 or 18.04 because of glibc versions)

chromium@bionic-pc:~$ '/home/chromium/Downloads/04-27-24/Chirp-next-20240427-x86_64.AppImage' 
Traceback (most recent call last):
  File "/tmp/.mount_Chirp-YmJePW/usr/bin/chirp", line 11, in <module>
    load_entry_point('chirp==0', 'console_scripts', 'chirp')()
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3.8/site-packages/chirp/wxui/__init__.py", line 9, in <module>
    from chirp import directory
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3.8/site-packages/chirp/directory.py", line 22, in <module>
    from chirp import chirp_common, errors
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3.8/site-packages/chirp/chirp_common.py", line 282, in <module>
    class Memory:
  File "/tmp/.mount_Chirp-YmJePW/usr/lib/python3.8/site-packages/chirp/chirp_common.py", line 297, in Memory
    power: PowerLevel | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by HarvestSnowpaw** [comment]
Just wanted to add that I have been having the same exact problem on a Gentoo Linux install. I am running stable, and get the exact same error as the OP.

**Comment by leirbag28** [comment]
Thank you for mentioning it. It appears no attention has been made to this issue yet...perhaps most are using the Mac or PC versions and Linux users have not yet upgraded their Chirp...but as I mentioned...the past for versions are very literally useless...they don't work at all. I just got a Tiddradio TD-H3 and was SUPER excited they made some fixes/progress on support for the TD-H3 but since none of these last 4 CHIRPS work..I can't do nothing and the TD-H3 is up and coming in popularity at the moment as it is the best Budget GMRS radio on the market. Luckily that LAST working version of CHIRP 
 (20240410) before these last 4 reads the TD-H3, so I can do SOME things on it for now.

**Comment by leirbag28** [comment]
FIRST; THANK YOU for opening up this issue again and putting together another release!  A Christmas Gift and New Years present!
Alas though, I get this error and it doesn't open:


chromium@bionic-pc:~$ '/home/chromium/AppImage/Chirp-next-20241227-x86_64.AppImage' 
Traceback (most recent call last):
  File "/tmp/.mount_Chirp-QIZNfv/usr/local/bin/chirp", line 8, in <module>
    sys.exit(chirpmain())
  File "/tmp/.mount_Chirp-QIZNfv/usr/local/lib/python3.10/dist-packages/chirp/wxui/__init__.py", line 145, in chirpmain
    import wx
  File "/tmp/.mount_Chirp-QIZNfv/usr/lib/python3/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_Chirp-QIZNfv/usr/lib/python3/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /tmp/.mount_Chirp-QIZNfv/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags

**Comment by goldstar611** [comment]
Just a note on the progress I've make: CHIRP is making use of newer python language features and thus is not compatible with the bundled python version 3.8. I'll look into bundling a newer version and see if that's compatible with older distributions like Ubuntu 18

**Comment by goldstar611** [comment]
I think this is resolved, although there is now an issue with a translation file but that is a new issue :)

- Upgraded bundled python version from 3.8 to 3.10 (by upgrading the package repository) in https://github.com/goldstar611/chirp-appimage/commit/50c56525b32d6a23c7a08a5da236d97afc8aa0ba
- Added libwayland-client0 in https://github.com/goldstar611/chirp-appimage/commit/fc6d3f46d940c4ed76dad5db076cce066765eead

The AppImage loads on Ubuntu 18.04.6 in my VMs.

**Comment by leirbag28** [comment]
> I think this is resolved, although there is now an issue with a translation file but that is a new issue :)
> 
> * Upgraded bundled python version from 3.8 to 3.10 (by upgrading the package repository) in [50c5652](https://github.com/goldstar611/chirp-appimage/commit/50c56525b32d6a23c7a08a5da236d97afc8aa0ba)
> * Added libwayland-client0 in [fc6d3f4](https://github.com/goldstar611/chirp-appimage/commit/fc6d3f46d940c4ed76dad5db076cce066765eead)
> 
> The AppImage loads on Ubuntu 18.04.6 in my VMs.

Just tested it on My Ubuntu 18.04.6 and it DOES indeed work! I had this error come up though and not quite sure what it means: 
08:40:31 PM: Invalid message catalog.
08:40:31 PM: '/tmp/.mount_Chirp-XlRqoM/usr/local/lib/python3.10/dist-packages/chirp/locale/en_US/LC_MESSAGES/CHIRP.mo' is not a valid message catalog.

But the App stil worked and I was able to copy frequencies from the Radio and also upload to the radio.
 Also it seems this update/fix you just did is labeled for 20241227 but categorized under release 20250103.  

Also great to know it is possible to Put a different version of Python that I don't have on my system (3.10) into the Appimage. This is such a great SuperPower. Solves problems galore.

**Comment by goldstar611** [comment]
> 08:40:31 PM: '/tmp/.mount_Chirp-XlRqoM/usr/local/lib/python3.10/dist-packages/chirp/locale/en_US/LC_MESSAGES/CHIRP.mo' is not a valid message catalog.
>
Well, at least we're making progress :)

> Also it seems this update/fix you just did is labeled for 20241227 but categorized under release 20250103.
> 
That is correct. I decided to use the upstream version (from chirpmyradio.com) now instead of the date that the AppImage was built. This will hopefully prevent any issues if someone uses the AppImage version of CHIRP and reports an issue over at chirpmyradio.com

> Also great to know it is possible to Put a different version of Python that I don't have on my system (3.10) into the Appimage. This is such a great SuperPower. Solves problems galore.
>
I am just using the great tools that the AppImage community has provided.

**Comment by goldstar611** [comment]
Let's track this "message catalog" error separately in https://github.com/goldstar611/chirp-appimage/issues/10
