### ISSUE TITLE
PLEASE PLEASE fix this already!  Last 4 or 5 versions of CHIRP appimage have NOT worked since version 20240410

### ISSUE THREAD

**Issue by leirbag28** [goldstar611/chirp-appimage#8]
Not a new issue but apparently the last 4 times I reported this it was CLOSED.

ALL the Last versions AFTER 20240410  have NOT worked and had the same error on Ubuntu 18.04.6 MATE and someone mentioned on Gentoo as well. I suspect not many are reporting it because they are NOT using the Appimage version or Ubuntu 18.04 at the same time with the Appimage. I believe this is the BEST current way to run this as Python is a major problem. Anyhow this is the same error I have gor the lat 4 or 5 versions when I drop the CHIRP Appimage into the MATE terminal because it doesn't open anyway:

Traceback (most recent call last):
  File "/tmp/.mount_Chirp-PgXjf9/usr/bin/chirp", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/tmp/.mount_Chirp-PgXjf9/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'suds' distribution was not found and is required by chirp

**Comment by Kiririnho** [comment]
Just wanted to chime in here that I am getting the same issue on Bazzite, which is an image-based distro built on Fedora.

I did not try any older releases but I did just try launching the newest release and it failed to launch.

**Comment by goldstar611** [comment]
New release dropped at https://github.com/goldstar611/chirp-appimage/releases/

Closing this duplicate issue in favor of #7
